### ISSUE TITLE
When will the code be available?

### ISSUE THREAD

**Issue by Sachin19** [yaolu/DeepRL_Summary#1]
I have implemented this code myself but I am not able to reproduce the results. Could you please let me know when you plan to publish this code, so that I can compare with mine?

**Comment by yaolu** [comment]
Sorry for the late reply.
I am currently working on other project. One of my colleague is implementing the paper now. I will let you know once the code is available. By the way, there should be someone else already implemented the paper, maybe you can search some related repos in github?

Yao
